### ISSUE TITLE
Where is the documentation for how the curent slots are to be used?

### ISSUE THREAD

**Issue by TheGrandmother** [Lundalogik/lime-web-components#214]
The documentation only mentions the deprecated usage of slots and only says that one should use the configurations in the edit view in the web client.

Although I can't find any documentation for how the json configuration for views. There are some small examples sprinkled around some of the examples. The tutorial for the [webclient start page](https://lundalogik.github.io/lime-web-components/versions/latest/#/webclient-start-page) has some info about this but it only focuses on the start page and I have been having issues reverse engineering it to work for cards.

Is the documentation for the view configuration available somewhere?

**Comment by adrianschmidt** [comment]
Hi! Yeah, the documentation is a little sparse at the moment, I'm sorry to say.

The new way of configuring where a component from an add-on shows up is to configure it in the new Lime Admin interface, but that requires the add-on to support that.

Are you currently developing an add-on yourself, or are you trying to configure an existing add-on?

**Comment by TheGrandmother** [comment]
Hi thanks for the quick reply!

I'm currently working on a new ad-don for a integration between lime and scrive.

I have followed the "Hello, CRM" tutorial and adapted it slightly.

**Comment by adrianschmidt** [comment]
Ok, great! It seems we don't actually have any more documentation finished than what you already found, but we'll of course help you out! I'll ask if a colleague who knows this stuff can help you out 😊

**Comment by TheGrandmother** [comment]
Thanks! <3

**Comment by adrianschmidt** [comment]
@jgroth will take a look at this tomorrow and see what he can do to help 🙂

**Comment by TheGrandmother** [comment]
Thanks! Life saver!
I'll continue MacGyvering and digging around until then :)

**Comment by adrianschmidt** [comment]
By the way, I can't find you in our system, so I'm guessing you're a third party developer? Do you have a contact you've already been talking to at Lime? I'm just asking so we can bring them up to speed about the new config too, and so they can be of better assistance in the future 🙂

**Comment by TheGrandmother** [comment]
Yupp!
I work on the integrations Team at Scrive.
I've been in contact with Erik Mangsten for some back-end help and with Rasmus Kahr for some general discussions and configuration help. But I haven't really talked to anything web client related with them.

@jgroth 
You can contact me on my scrive address henrik.sommerland@scrive.com tomorrow!

**Comment by jgroth** [comment]
I'm replying here in case someone else also has the same issue :slightly_smiling_face: 

The current documentation is a little bit ahead of it's time since the functionality regarding the new way of configuring the addons has yet to be released. When the new version is released, you should also no longer have to manually write JSON to configure the webclient and instead use a form with fields of all available options. This will make it more clear of what can be configured and how to do it. Within this form it will be possible to configure what addons to place it what slots.

It's still safe to use the old deprecated way to place the addons in the slots, and it will not be removed in the next version either. It will probably be removed in the version after that though... Upgrading to the new way should be quite straight forward

Hope this helps! :slightly_smiling_face:

**Comment by TheGrandmother** [comment]
@jgroth 
Thanks!

Oki! Is there any approximate timeline for when this will be released?

**Comment by adrianschmidt** [comment]
> Is there any approximate timeline for when this will be released?

@magnusfagerlund @FlippAre Ping!

**Comment by FlippAre** [comment]
An RC of the new on-prem installer is set for today. Release in august

**Comment by adrianschmidt** [comment]
@TheGrandmother Would you consider this resolved for now? If so, I'll close it.

**Comment by adrianschmidt** [comment]
### 😆

I was like "Where did the issue go? Did GitHub autoclose it?!" then "Ah… 😄"
