### ISSUE TITLE
add `ui` property to the LimeType interface

### ISSUE THREAD

**Issue by Befkadu1** [Lundalogik/lime-web-components#491]
I am not sure if the `ui` property is forgotten for the new `LimeType` interface [here](https://github.com/Lundalogik/lime-web-components/blob/main/packages/lime-web-components/src/limetype/limetype.ts) 

The `ui` look like this

``` 
ui: {
        icon: 'organization',
        color: 'lime-blue',
        create: true,
        descriptive: ['name'],
    }

**Comment by adrianschmidt** [comment]
@Befkadu1 I found why it wasn't failing when using the `Limetype` exported from the old package. The old `Limetype` explicitly allowed any property name:

<img width="657" alt=" " src="https://user-images.githubusercontent.com/154725/182556967-303ed6f2-480b-4825-a89b-1d5de018fce7.png">

https://github.com/Lundalogik/lime-web-components/blob/1982ee35e074f74683c49edf56cd24a5b0657b09/packages/interfaces/src/limetype.interface.ts#L25

**Comment by adrianschmidt** [comment]
@jgroth Hey! (If you see this while on vacation, it's totally OK to ignore until you're back at work.) We've looked into this during standup today, and @Befkadu1 had found that you've previously made the following change in lime-crm-components, when refactoring to use the new lime-web-components package:

<img width="713" alt="Screenshot showing a function argument which has had its typing changed from `Limetype` to `Limetype & { ui?: any }`" src="https://user-images.githubusercontent.com/154725/182554923-9cb28b8e-ffc5-4707-95c2-d524ea6ecae5.png">

(The commit is [here](https://github.com/Lundalogik/lime-crm-components/commit/496871bcf7999c8b69ca80cf82c0384198a3af18), but I can't link straight to the diff for that file, because the diff is too big for all files to be loaded 🤦‍♂️)

We're not sure about the reason for not adding the `ui` property to the interface (did you just want to limit the necessary changes, do you think it doesn't belong there, something else).

**Comment by jgroth** [comment]
Yeah I don't think it really belongs there, it's a bit of a weird place to have it so that's why I removed it. It's not available in the backend and wanted the interfaces to match as closely as possible

**Comment by Befkadu1** [comment]
>  Yeah I don't think it really belongs there, it's a bit of a weird place to have it so that's why I removed it. It's not available in > the backend and wanted the interfaces to match as closely as possible

Yea it doesn't seem it belongs there, we can get the icon and color from `GeneralViewConfig` [here](https://github.com/Lundalogik/lime-crm-components/blob/7f88a9fa65485318f37ff5598fa55fb2e3779e06/src/core/config/views-config.types.ts#L86). Then is is a right approach to get the icon

```
export function getIcon(limetype: Limetype & { ui?: any }) {
    return limetype?.ui?.icon;
}
```

Or should we keep on doing like you did above `limetype: Limetype & { ui?: any }` whenever we want to get the icon?

**Comment by jgroth** [comment]
We should probably get it from the config instead. It will remain on the limetype for a while even though it's not on the interface since some customizations might use it

**Comment by Befkadu1** [comment]
Then I am closing this issue and create a new issue to get the `ui` from the config instead otherwise we will forget it.
